### ISSUE TITLE
selectByHsvColor() not working

### ISSUE THREAD

**Issue by kovaszab** [skydoves/ColorPickerView#77]
- Library Version [e.g. v2.2.3] (tried multiple versions)
- SDK 30 
 
**Describe the Bug:**

When I try to `selectByHsvColor()` I get an error saying:

```
selectByHsvColor(@ColorInt int color) can be called only when the palette is an instance of ColorHsvPalette. Use setHsvPaletteDrawable();
```
But when I try to `setHsvPaletteDrawable()` I get an error:

```
 java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1113)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1080)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1030)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:991)
        at com.skydoves.colorpickerview.ColorPickerView.setHsvPaletteDrawable(ColorPickerView.java:741)
```

I don't use a custom Palette Drawable.

I have my ColorPicker in my main activity like this:

```
<com.skydoves.colorpickerview.ColorPickerView
        android:layout_width="300px"
        android:layout_height="300px"
        android:id="@+id/colorPickerView"
        >
</com.skydoves.colorpickerview.ColorPickerView>
```

**Expected Behavior:**

`selectByHsv()` should work since I don't use custom Palette Drawable.

**Comment by kovaszab** [comment]
Sorry forgot to mention, above I tried setting `layout_width` and `layout_height ` with pixel value, to check if maybe that is the problem. But neither `dp` nor `px` didn't work.

**Comment by skydoves** [comment]
Sorry for the late reply.
Could you please run the demo project? Also, the demo project is [the same attributes](https://github.com/skydoves/ColorPickerView/blob/master/app/src/main/res/layout/activity_main.xml#L46) on ColorPickerView.

**Comment by KingVanti** [comment]
I have a very similar issue. I'm using databinding to bind to the hsv value of the color-picker using a custom binding-adapter.
```
<com.skydoves.colorpickerview.ColorPickerView
            android:id="@+id/picker"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            app:hsv="@{viewModel.hsv}"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintDimensionRatio="H,1:1"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent" />
```
As you can see, the height is 0, but that should not be a problem, since it should be expanded by the constraints.
Next lets look at the adapter:
```
@BindingAdapter("app:hsv")
fun ColorPickerView.setHSV(hsv: HSV) {
    this.selectByHsvColor(hsv.asColorInt())
}
```
Straightforward. I get the following exception on opening the fragment:
`Caused by: java.lang.IllegalAccessException: selectByHsvColor(@ColorInt int color) can be called only when the palette is an instance of ColorHsvPalette. Use setHsvPaletteDrawable();`

Weird error since I never specified a different palette, but ok, edited my code to:
```
@BindingAdapter("app:hsv")
fun ColorPickerView.setHSV(hsv: HSV) {
    this.setHsvPaletteDrawable()
    this.selectByHsvColor(hsv.asColorInt())
}
```
Now I get:
`Caused by: java.lang.IllegalArgumentException: width and height must be > 0`

Hope you can help me with this one.

**Comment by skydoves** [comment]
Hey @KingVanti,
Could you build with like this?

```kotlin
post {
 this.setHsvPaletteDrawable()
 this.selectByHsvColor(hsv.asColorInt())
}
```
Thanks!

**Comment by KingVanti** [comment]
@skydoves, thanks that worked. Might want to integrate that into the `setHsvPaletteDrawable` call itself and release a new version with that.
